### PR TITLE
Make Web Compatible

### PR DESCRIPTION
**Pull request by AdamRaichu**
I tried to make the extension web compatible by omitting use of path and fs and using vscode apis instead.

### CODE REVIEW

**Comment by AdamRaichu** [comment]
Ah, the problem was trying to load a script over raw.githubusercontent.com which is text/plain.

**Comment by AdamRaichu** [comment]
Testable by [opening the repo in vscode web](https://vscode.dev/github/AdamRaichu/snowstorm/tree/master) and running the command `Developer: Install extension from location...` and pasting in the url `https://adamraichu.github.io/snowstorm/vscode_extension/`. Then open `./examples/<any>.particle.json`.

**Comment by JannisX11** [comment]
That's interesting that this works. But it looks like it doesn't load in textures, at least on my end. Is that something that is fixable?

**Comment by AdamRaichu** [comment]
> That's interesting that this works. But it looks like it doesn't load in textures, at least on my end. Is that something that is fixable?

I don't know how textures are loaded or where they are loaded from. Could you point me to the relevant section of code?

**Comment by AdamRaichu** [comment]
```
Uncaught (in promise) Error: [UriError]: cannot call joinPath on URI without path
    at Function.joinPath (uri.ts:351:10)
    at eval (web.js:81:37)
    at R.invoke (event.ts:723:17)
    at b.deliver (event.ts:936:22)
    at D.fire (event.ts:892:24)
    at f.$onMessage (extHostWebview.ts:215:30)
    at o.N (rpcProtocol.ts:455:17)
    at o.M (rpcProtocol.ts:440:32)
    at o.H (rpcProtocol.ts:370:19)
    at o.G (rpcProtocol.ts:305:10)
    at eval (rpcProtocol.ts:161:42)
    at R.invoke (event.ts:723:17)
    at b.deliver (event.ts:936:22)
    at D.fire (event.ts:892:24)
    at MessagePort.u.port1.onmessage (extensionHostWorker.ts:201:12)
```

It looks like I found the problem. I try to call `vscode.Uri.joinPath` with a first argument that is not of type `vscode.Uri`.

https://github.com/AdamRaichu/snowstorm/blob/2b8e2da875393ebc02e9dc37a3d2b2941d4fdad8/vscode_extension/src/web.js#L79-L82

**Comment by AdamRaichu** [comment]
Particles are now loading correctly.

**Comment by AdamRaichu** [comment]
Fun fact: the web version should also work on other platforms. If `{package.json}.main` was pointed to web.js you could delete extension.js and snowstormEditor.js, which I would recommend so you don't have to maintain two files that are supposed to be identical (web.js needs to contain snowstormEditor.js).

**Comment by AdamRaichu** [comment]
@JannisX11 this should work correctly now.

**Comment by JannisX11** [comment]
I haven't really worked on this project in almost a year. I'm doing some things on it now, so I'm hoping I'll be able to take a look at this PR as well, but I can't promise anything yet.

**Comment by AdamRaichu** [comment]
Going to close this and redo.

**Pull request closed without merging**
